SET FOREIGN_KEY_CHECKS = 0;
drop table if exists appointment;
drop table if exists customer;
drop table if exists owner;
drop table if exists restaurant;
drop table if exists `table`;
drop table if exists user;
drop table if exists waiter;
drop table if exists appointment2user;
SET FOREIGN_KEY_CHECKS = 1;